name: Scraper Worker

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Autenticación con Google
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar scraper
        run: node scripts/scrape.js
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}

      - name: Commit de resultados
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/results.json
          git commit -m "update data" || echo "No changes"
          git push
