name: Scraper Worker

on:
  schedule:
    - cron: "*/10 * * * *" # cada 10 minutos
  workflow_dispatch: # ejecutarlo manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write


    steps:
      - uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar scraper
        run: node scripts/scrape.js

      - name: Commit de resultados
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/results.json
          git commit -m "update data" || echo "No changes"
          git push
